"""profile pic filename

Revision ID: 985c3daee9b2
Revises: a99efd8f0700
Create Date: 2020-05-12 22:06:26.945524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '985c3daee9b2'
down_revision = 'a99efd8f0700'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_pic_filename', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_pic_filename')
    # ### end Alembic commands ###
