"""Tables

Revision ID: a99efd8f0700
Revises: 
Create Date: 2020-05-11 15:03:00.029106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a99efd8f0700'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('sin_rad_lat', sa.Float(), nullable=True),
    sa.Column('cos_rad_lat', sa.Float(), nullable=True),
    sa.Column('rad_lng', sa.Float(), nullable=True),
    sa.Column('username', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('has_previous_explore_search', sa.Boolean(), nullable=True),
    sa.Column('previous_explore_location', sa.String(length=120), nullable=True),
    sa.Column('previous_explore_latitude', sa.Float(), nullable=True),
    sa.Column('previous_explore_longitude', sa.Float(), nullable=True),
    sa.Column('previous_explore_sin_rad_lat', sa.Float(), nullable=True),
    sa.Column('previous_explore_cos_rad_lat', sa.Float(), nullable=True),
    sa.Column('previous_explore_rad_lng', sa.Float(), nullable=True),
    sa.Column('previous_explore_radius', sa.Float(), nullable=True),
    sa.Column('previous_explore_skill', sa.String(length=20), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    op.create_table('application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('response', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_content'), 'application', ['content'], unique=False)
    op.create_index(op.f('ix_application_title'), 'application', ['title'], unique=False)
    op.create_table('befriends',
    sa.Column('befriend_id', sa.Integer(), nullable=True),
    sa.Column('befriended_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['befriend_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['befriended_id'], ['user.id'], )
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_content'), 'message', ['content'], unique=False)
    op.create_table('skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=20), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_title'), 'skill', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skill_title'), table_name='skill')
    op.drop_table('skill')
    op.drop_index(op.f('ix_message_content'), table_name='message')
    op.drop_table('message')
    op.drop_table('befriends')
    op.drop_index(op.f('ix_application_title'), table_name='application')
    op.drop_index(op.f('ix_application_content'), table_name='application')
    op.drop_table('application')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
