"""Tables

Revision ID: df97a244544e
Revises: 
Create Date: 2020-07-02 18:14:12.665650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df97a244544e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('picture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=25), nullable=True),
    sa.Column('path', sa.String(length=2048), nullable=True),
    sa.Column('replacement', sa.String(length=2048), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('handle', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('privacy', sa.String(length=7), nullable=True),
    sa.Column('location_is_fixed', sa.Boolean(), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('sin_rad_lat', sa.Float(), nullable=True),
    sa.Column('cos_rad_lat', sa.Float(), nullable=True),
    sa.Column('rad_lng', sa.Float(), nullable=True),
    sa.Column('profile_pic_id', sa.Integer(), nullable=True),
    sa.Column('cover_pic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cover_pic_id'], ['picture.id'], ),
    sa.ForeignKeyConstraint(['profile_pic_id'], ['picture.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_handle'), 'group', ['handle'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('birthdate', sa.DateTime(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('sin_rad_lat', sa.Float(), nullable=True),
    sa.Column('cos_rad_lat', sa.Float(), nullable=True),
    sa.Column('rad_lng', sa.Float(), nullable=True),
    sa.Column('username', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('profile_pic_id', sa.Integer(), nullable=True),
    sa.Column('cover_pic_id', sa.Integer(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cover_pic_id'], ['picture.id'], ),
    sa.ForeignKeyConstraint(['profile_pic_id'], ['picture.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('response', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_content'), 'application', ['content'], unique=False)
    op.create_index(op.f('ix_application_title'), 'application', ['title'], unique=False)
    op.create_table('befriends',
    sa.Column('befriend_id', sa.Integer(), nullable=True),
    sa.Column('befriended_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['befriend_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['befriended_id'], ['user.id'], )
    )
    op.create_table('group_to_group',
    sa.Column('megagroup_id', sa.Integer(), nullable=False),
    sa.Column('microgroup_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['megagroup_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['microgroup_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('megagroup_id', 'microgroup_id')
    )
    op.create_table('groups',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('membership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_content'), 'message', ['content'], unique=False)
    op.create_table('skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=20), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_title'), 'skill', ['title'], unique=False)
    op.create_table('permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=20), nullable=True),
    sa.Column('membership_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['membership_id'], ['membership.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permission_title'), 'permission', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_permission_title'), table_name='permission')
    op.drop_table('permission')
    op.drop_index(op.f('ix_skill_title'), table_name='skill')
    op.drop_table('skill')
    op.drop_index(op.f('ix_message_content'), table_name='message')
    op.drop_table('message')
    op.drop_table('membership')
    op.drop_table('groups')
    op.drop_table('group_to_group')
    op.drop_table('befriends')
    op.drop_index(op.f('ix_application_title'), table_name='application')
    op.drop_index(op.f('ix_application_content'), table_name='application')
    op.drop_table('application')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_group_handle'), table_name='group')
    op.drop_table('group')
    op.drop_table('picture')
    # ### end Alembic commands ###
